[build]
  functions = "netlify/functions"
  command = "npm run build"
  publish = "dist"

[dev]
  framework = "vite"
  command = "npm run dev"
  targetPort = 5173
  publish = "dist"

[functions]
  node_bundler = "esbuild"

# La fonction cleanup a déjà son schedule défini dans son code
# donc pas besoin de le redéfinir ici